
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_project_webapp?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jiebin22